/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 nike2.glb 
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useEffect, useRef } from 'react'

export default function Nike2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./nike_statue/nike2.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=> {
    actions.metarigAction.play();

})
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig" position={[-2.833, -5.53, -3.01]} rotation={[Math.PI, -3.36, Math.PI]} scale={4.5}>
          <mesh>
          <hemisphereLight intensity={0.15} groundColor='black' />
          <spotLight
            position={[20, 25, 40]}
            angle={0.12}
            penumbra={1}
            intensity={1}
            castShadow
            shadow-mapSize={1024}
          />
          <pointLight intensity={1} />
          <primitive object={nodes.spine} />
          <skinnedMesh name="defaultMaterial" geometry={nodes.defaultMaterial.geometry} material={materials.Nike_LowPoly} skeleton={nodes.defaultMaterial.skeleton} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./nike_statue/nike2.glb')
