/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 nike2.glb 
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useEffect, useRef } from 'react'

export default function Nike2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/nike2.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=> {
    actions.metarigAction.play();

})
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig" position={[-2.833, -5.53, -3.01]} rotation={[Math.PI, -3.36, Math.PI]} scale={4.5}>
          <primitive object={nodes.spine} />
          <skinnedMesh name="defaultMaterial" geometry={nodes.defaultMaterial.geometry} material={materials.Nike_LowPoly} skeleton={nodes.defaultMaterial.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/nike2.glb')
